# Generated by Django 2.0.7 on 2018-09-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='members',
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.GroupModel'),
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
    ]
